[workspace]
semver_check = true

[[package]]
name = "stac"

[[package]]
name = "stac-duckdb"

[[package]]
name = "stac-extensions"

[[package]]
name = "stac-io"

[[package]]
name = "pgstac"

[[package]]
name = "stac-server"

[[package]]
name = "stac-validate"

[[package]]
name = "stac-wasm"
release = false

[[package]]
name = "rustac"
semver_check = false
